version: '3.8'
services:
  mnist-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./saved_images:/app/saved_images  # 로컬과 동기화
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
